{% set name = "PyCifRW" %}
{% set version = "4.4" %}
{% set sha256 = "f365ed97991738a99722e08afe772fe197bf7f40dfc0a210d524e7742ad81ff8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - CifFile.StarFile
    - CifFile.StarScan

about:
  home: https://bitbucket.org/jamesrhester/pycifrw/overview
  license: PSF-2-like
  license_family: other
  license_file: LICENSE
  summary: 'CIF file support for Python'

  description: |
    PyCIFRW provides support for reading and writing CIF (Crystallographic
    Information Format) files using Python. It was developed at the Australian
    National Beamline Facility (ANBF), run by the Australian Synchrotron
    Research Program (ASRP), as part of a larger project to provide CIF
    input/output capabilities for data collection. It is now (Mar 2017)
    maintained and developed within the Australian Nuclear Science and
    Technology Organisation (ANSTO).
  doc_url: https://bitbucket.org/jamesrhester/pycifrw/overview
  dev_url: https://bitbucket.org/jamesrhester/pycifrw/overview

extra:
  recipe-maintainers:
    - CJ-Wright
    - pavoljuhas
