package:
  name: pycifrw
  version: !!str 3.6.2

source:
  fn: PyCifRW-3.6.2.tar.gz
  url: https://pypi.python.org/packages/source/P/PyCifRW/PyCifRW-3.6.2.tar.gz
  md5: 3f1f6ea26ba3654d6a361a89b1fea480
  patches:
   # List any patch files here
    - flex.patch
    - sets.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pycifrw = pycifrw:main
    #
    # Would create an entry point called pycifrw that calls pycifrw.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - CifFile
    - StarFile
    - StarScan

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/jamesrhester/pycifrw/overview
  license: Python Software Foundation License
  summary: 'CIF/STAR file support for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
