{% set name = "libdiffpy" %}
{% set version = "1.4.0" %}
{% set sha256 = "0b08e161e8f2ed517ace9223c0315258c492c626d84dd06ff23ad9293c16e161" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libdiffpy', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - scons
  host:
    - libboost {{ boost }}
    - gsl {{ gsl }}
    - libobjcryst {{ libobjcryst }}

  run:
    # NOTE libobjcryst is implicitly added by libobjcryst run_exports
    - libboost
    - {{ pin_compatible('gsl', min_pin='x.x', max_pin='x') }}

test:
  requires:
    - {{ compiler('cxx') }}
    - cxxtest
    - scons

  source_files:
    - SConstruct
    - site_scons/
    - src/SConscript
    - src/SConscript.configure
    - src/tests/

  # commands:
    # Execute the run_test.sh script.

about:
  home: https://github.com/diffpy/libdiffpy
  summary: C++ calculators of PDF, bond valence sum and other pair quantities.
  license: Modified BSD License
  license_file: LICENSE.txt
