package:
  name: libdiffpy
  ## Use __conda_version__.txt.
  # version: 1.3

source:
  fn: libdiffpy-1.3.1.tar.gz
  url: https://github.com/diffpy/libdiffpy/releases/download/v1.3.1/libdiffpy-1.3.1.tar.gz
  md5: a4b2215c657f31564c156168f4255228
  # git_url: https://github.com/diffpy/libdiffpy.git
  # git_rev: master

build:
  number: 0

requirements:
  build:
    - scons
    - boost-all 1.59.0
    - gsl 2.1
    - cxxtest
    - libobjcryst 2015.1|2015.1.*

  run:
    - boost-all 1.59.0
    - gsl >=2.1
    - libobjcryst 2015.1|2015.1.*

test:
  requires:
    - scons

  commands:
    # Run unit-test program with the installed shared library.
    # Make sure tests cannot use library file from the source directory.
    - scons -C "$SRC_DIR" --clean lib
    - export LD_LIBRARY_PATH="${PREFIX}/lib"                    # [linux]
    - export DYLD_FALLBACK_LIBRARY_PATH="${PREFIX}/lib"         # [osx]
    - ALLTESTSFAST=$(ls -t ${SRC_DIR}/build/fast*/tests/alltests | head -1)
    - "${ALLTESTSFAST}"

about:
  home: https://github.com/diffpy/libdiffpy
  summary: C++ calculators of PDF, bond valence sum and other pair quantities.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
