package:
  name: libobjcryst
  version: 1.9.8

source:
  git_url: https://github.com/diffpy/libobjcryst.git
  git_rev: 3dfc2d3a7b0f756ba89fbdfe25975e836a223810

  # fn: libobjcryst-1.9.8.tar.gz
  # url: https://github.com/diffpy/libobjcryst/releases/download/v1.9.8/libobjcryst-1.9.8.tar.gz

build:
  number: 6
  binary_relocation: False      # [linux]

requirements:
  build:
    - scons
    - boost                     # [linux]
    - boost 1.56.0 py27_2       # [osx]

about:
  home: https://github.com/diffpy/libobjcryst/
  license: GPLv2
  license_file: LICENSE.txt
