{% set name = "pyobjcryst" %}
{% set version = "2.0.2" %}
{% set md5 = "c7af2e1078a52c26b5d4ebd7439f6731" %}

package:
  name: {{name}}
  version: {{version}}

source:
  fn: {{name}}-{{version}}.tar.gz
  url: https://pypi.io/packages/source/{{name[0]}}/{{name}}/{{name}}-{{version}}.tar.gz
  md5: {{md5}}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy 1.11.2
    - libobjcryst 2017.1.*
    - boost 1.61.0

  run:
    - python
    - setuptools
    - numpy >=1.11.2
    - libobjcryst 2017.1.*
    - boost 1.61.0

test:
  # Python imports
  imports:
    - pyobjcryst
    - pyobjcryst.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/pyobjcryst
  summary: Python bindings to the ObjCryst++ crystallographic library.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
