package:
  name: diffpy.srreal
  ## Use __conda_version__.txt.
  # version: "1.1a0"

source:
  git_url: https://github.com/diffpy/diffpy.srreal
  git_rev: fe3e97fc34b85080c0982e4bdd1ae5f217293fa2

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.3
    - libdiffpy
    - pycifrw
    - diffpy.structure
    - scons

  run:
    - python
    - setuptools
    - numpy >=1.3
    - libdiffpy
    - pycifrw
    - diffpy.structure
    - pyobjcryst
    - periodictable

test:
  # Python imports
  imports:
    - diffpy
    - diffpy.srreal
    - diffpy.srreal.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/diffpy.srreal
  summary: Calculators for PDF, bond valence sum and other
    pair-interaction quantities.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
