package:
  name: diffpy.srreal
  ## Use __conda_version__.txt.
  # version: "1.1a0"

source:
  fn: diffpy.srreal-1.1.tar.gz
  url: https://pypi.python.org/packages/source/d/diffpy.srreal/diffpy.srreal-1.1.tar.gz
  md5: 6cd6ca02aa244ae268f39686991efac9
  # git_url: https://github.com/diffpy/diffpy.srreal
  # git_rev: master

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy 1.9.2
    - libdiffpy 1.3.1
    - libobjcryst 2015.1.2
    - pycifrw
    - diffpy.structure
    - scons

  run:
    - python
    - setuptools
    - numpy >=1.9.2
    - libdiffpy 1.3.1
    - pycifrw
    - diffpy.structure
    - pyobjcryst 2.0*
    - periodictable

test:
  # Python imports
  imports:
    - diffpy
    - diffpy.srreal
    - diffpy.srreal.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/diffpy.srreal
  summary: Calculators for PDF, bond valence sum and other
    pair-interaction quantities.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
