package:
  name: srfit-sasview
  version: !!str 3.1.1

source:
  fn: sasview-3.1.1.tar.gz
  url: https://github.com/SasView/sasview/archive/v3.1.1.tar.gz
  sha256: a52544af7c4bb86b9899e855fef3ad69fa51f5827f07db31932afe01284dd186
  patches:
    - srfit-sasview-setup.patch

build:
  # make it easy to see that sas package belongs to us
  preserve_egg_dir: True
  # compiled modules use only system libraries.
  binary_relocation: False

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - numpy 1.9.2

  run:
    - python
    - numpy >=1.9.2
    - scipy
    - lxml

test:
  # Python imports
  imports:
    - sas.data_util
    - sas.dataloader
    - sas.models
    - sas.pr

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pylint

about:
  home: http://www.sasview.org/
  license: PSF
  summary: 'Selected modules from the SasView application.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
