package:
  name: diffpy.structure
  version: "1.3a1"

source:
  git_url: https://github.com/diffpy/diffpy.Structure
  git_tag: v1.3a1
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - diffpy.structure = diffpy.structure:main
    #
    # Would create an entry point called diffpy.structure that calls diffpy.structure.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 0

requirements:
  build:
    - python
    - setuptools
    - pycifrw <4

  run:
    - python
    - setuptools
    - numpy >=1.3
    - pycifrw <4

test:
  # Python imports
  imports:
    - diffpy
    - diffpy.Structure
    - diffpy.Structure.Parsers
    - diffpy.Structure.applications
    - diffpy.Structure.expansion
    - diffpy.Structure.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/diffpy.Structure
  license: BSD License
  summary: 'Crystal structure container and parsers for structure formats.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
