{% set name = "periodictable" %}
{% set version = "1.5.0" %}
{% set sha256 = "b020c04c6765d21903e4604a76ca33cda98677003fe6eb48ed3690cfb03253b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    - test-with-round-off-tolerance.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pyparsing

test:
  imports:
    - periodictable
    - periodictable.density

  source_files:
    - test

  commands:
    - nosetests -v -w test

  requires:
    - nose

about:
  home: http://www.reflectometry.org/danse/elements.html
  license: Public domain
  summary: 'Extensible periodic table for python'

  description: |
    The periodictable package provides an extensible periodic table
    of the elements prepopulated with data important to neutron and
    X-ray scattering experiments. With the elements pacakge you can
    compute the scattering potential of a compound at a given wavelength.
  doc_url: http://www.reflectometry.org/danse/docs/elements/
  dev_url: https://github.com/pkienzle/periodictable

extra:
  recipe-maintainers:
    - bjodah
    - pavoljuhas
