package:
  name: cxxtest
  version: "4.4"

source:
  fn: cxxtest-4.4.tar.gz
  url: https://github.com/CxxTest/cxxtest/releases/download/4.4/cxxtest-4.4.tar.gz
  sha256: 1c154fef91c65dbf1cd4519af7ade70a61d85a923b6e0c0b007dc7f4895cf7d8

build:
  number: 2
  noarch: python

requirements:
  run:
    - python

test:
  source_files:
    - doc/examples/MyTestSuite1.h

  commands:
    # provided in run_test.sh

about:
  home: http://cxxtest.com/
  license: GPL 3
  summary: "CxxTest Unit Testing Framework."
