package:
  name: diffpy-cmi
  version: 2.0a2

build:
  number: 1

requirements:
  run:
    - diffpy.structure 1.3
    - diffpy.utils 1.2
    - pyobjcryst 1.0.post12 py27_0      [linux]
    - pyobjcryst 1.0.post12 py27_1      [osx]
    - periodictable 1.4.1
    - diffpy.srreal <=1.1
    - diffpy.srfit 1.1a0.*
    - srfit-sasview
    - ipython
    - ipyparallel
    - scipy

test:
  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

about:
  home: http://www.diffpy.org/products/diffpycmi/
  summary: Tools for complex modeling of materials structures from diffractiona data.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
