package:
  name: diffpy-cmi
  version: 3.0.1

build:
  number: 0

requirements:
  host:
    # we need per-python packages, because srfit-sasview is only for py27
    - python {{ python }}

  run:
    # Python 2
    - srfit-sasview 3.1.2       # [py2k]

    # Python 3 and 2
    - diffpy.structure 3.0.1
    - diffpy.utils 3.0.0
    - diffpy.srfit 3.0.0
    - libobjcryst 2017.2.2
    - pyobjcryst 2.1.0
    - periodictable 1.5.0
    - libdiffpy 1.4.0
    - diffpy.srreal 1.3.0

    - python
    - ipython
    - jupyter
    - scipy
    - matplotlib

test:
  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

about:
  home: http://www.diffpy.org/products/diffpycmi/
  summary: Tools for complex modeling of materials structures from diffractiona data.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
