package:
  name: diffpy-cmi
  version: 2.1          # [py2k]
  version: 3.0a0        # [py3k]

build:
  number: 0

requirements:
  run:

    # Python 2
    - diffpy.structure 1.3.5    # [py2k]
    - diffpy.utils 1.2.2        # [py2k]
    - diffpy.srfit 1.3          # [py2k]
    - srfit-sasview 3.1.2       # [py2k]

    # Python 3
    - diffpy.utils 3.0a2        # [py3k]
    - diffpy.structure 3.0a2    # [py3k]
    - diffpy.srfit 3.0a0        # [py3k]

    # Python 3 and 2
    - libobjcryst 2017.1.1
    - pyobjcryst 2.0.2
    - periodictable 1.5.0
    - libdiffpy 1.3.4
    - diffpy.srreal 1.2

    - ipython
    - jupyter
    - scipy
    - matplotlib

test:
  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

about:
  home: http://www.diffpy.org/products/diffpycmi/
  summary: Tools for complex modeling of materials structures from diffractiona data.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
