package:
  name: diffpy-cmi
  version: 2.1

build:
  number: 0

requirements:
  run:
    - diffpy.structure 1.3.5
    - diffpy.utils 1.2.2
    - libobjcryst 2017.1.1
    - pyobjcryst 2.0.2
    - periodictable 1.5.0
    - libdiffpy 1.3.4
    - diffpy.srreal 1.2
    - diffpy.srfit 1.3
    - srfit-sasview 3.1.2
    - ipython
    - ipyparallel
    - jupyter
    - scipy
    - matplotlib

test:
  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

about:
  home: http://www.diffpy.org/products/diffpycmi/
  summary: Tools for complex modeling of materials structures from diffractiona data.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
