package:
  name: diffpy.utils
  ## Use __conda_version__.txt.

source:
  fn: diffpy.utils-1.2.1.tar.gz
  url: https://pypi.python.org/packages/source/d/diffpy.utils/diffpy.utils-1.2.1.tar.gz
  md5: 1678f7e65782ef0219071157554726e6
  # git_url: https://github.com/diffpy/diffpy.utils
  # git_rev: master

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy >=1.3

test:
  # Python imports
  imports:
    - diffpy
    - diffpy.utils
    - diffpy.utils.parsers
    - diffpy.utils.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/diffpy.utils/
  summary: Shared utilities for diffpy packages.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
