package:
  name: gsl
  version: 2.1

source:
  fn: gsl-2.1.tar.gz
  url: http://ftpmirror.gnu.org/gsl/gsl-2.1.tar.gz
  sha256: 59ad06837397617f698975c494fe7b2b698739a59e2fcf830b776428938a0c66

build:
  number: 0

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL 3
